### ISSUE TITLE
I am trying to create the pixie datasource by connecting to pixie cloud to create dashboard and looking details for datasource.yaml values

### ISSUE THREAD

**Issue by laxmansoma1903-zz** [pixie-io/grafana-plugin#54]
@zasgar

What happened:
I am trying to create the pixie datasource by connecting to pixie cloud to create dashboard.

What you expected to happen:
datasource should be created with clusterid and apikey added , but instead its creating the datasource without the values being added automatically.

How to reproduce it (as minimally and precisely as possible):
datasourcesgrafana.yaml:
apiVersion: 1
datasources:

access: proxy
name: Pixie Grafana Datasource Plugin
editable: true
isDefault: true
type: pixie-pixie-datasource
Pixie API Key: xxxxxx
Cluster ID: xxxxxx
Pixie Cloud address: withpixie.ai:443
orgId: 1
jsonData:
timeInterval: 5s
Anything else we need to know?:

Environment:

Grafana version:
Data source type & version:pixie
OS Grafana is installed on:linux
User OS & Browser:
Grafana plugins:pixie-datasource

**Comment by TarasPriadka** [comment]
Hi, are you trying to run provisioned grafana? You can take a look at Pixie provisioning code in the main repo for a [demo application](https://github.com/pixie-io/pixie/tree/main/k8s/grafana_demo). You would want to take a look at [grafana-datasources.yaml](https://github.com/pixie-io/pixie/blob/main/k8s/grafana_demo/), and how those get pulled into grafana provisioning [here](https://github.com/pixie-io/pixie/blob/13a76ecebc55ec9ea77f8de0b0cc35fc1dfaed12/k8s/grafana_demo/grafana-deployment.yaml#L130-L133).

You might want to also use the [latest release](https://github.com/pixie-io/grafana-plugin/releases/download/v0.0.3/pixie-pixie-datasource-0.0.3.zip) which includes a lot of improvements to the current plugin. 

Also, the `cluster id` got removed from the plugin config in the latest release. You have to use `pixieCluster` dashboard variable which automatically queries all of the clusters associated with the API key. You would have to go to: Your Dashboard -> Settings -> Variables -> Add new query variable with name `pixieCluster` and select `Clusters` from the dropdown.

**Comment by laxmansoma1903** [comment]
Thanks Taras for getting back and providing required documentation , also how do you pass the cluster ID while you create the datasource which I don't see that.

**Comment by TarasPriadka** [comment]
We decided to remove cluster ID from the configuration. You have to create a dashboard variable using steps: Your Dashboard -> Settings -> Variables -> Add new query variable with name pixieCluster and select Clusters from the dropdown. This will create a dashboard scoped variable which will query all the clusters which are associated with your Pixie account.

**Comment by laxmansoma1903** [comment]
Hi Taras - As part of Helm chart , we want to automate everything for many GKE cluster which we maintain and we don't want anything manually from the grafana console to retrieve the cluster details from pixie...

**Comment by TarasPriadka** [comment]
Yes that makes sense. Are you also provisioning dashboards? If you do, you can provision dashboards which have declared dashboard variables so that you don't have to do anything manually. I see the necessity of having the clusterID in the config, but if you want to work around this for now, you can declare dashboard jsons like [this](https://github.com/pixie-io/grafana-plugin/blob/main/dashboards/px_cluster.json)(or download and use it from pixie repo). Specifically take a look at how dashboard variables are declared [there](https://github.com/pixie-io/grafana-plugin/blob/d949a605dcfa27b8b1c918b6db8e2744002e0c51/dashboards/px_cluster.json#L737-L760).

**Comment by laxmansoma1903** [comment]
Thanks Taras for your input ,how ever we able to workaround by passing the values as below to create datasource as part of our helm automation.

datasourcesgrafana.yaml:
   apiVersion: 1
   datasources:  
   - access: proxy
     name: Pixie Grafana Datasource Plugin
     editable: true
     isDefault: true
     type: pixie-pixie-datasource
      jsonData:
        timeInterval: 5s
     secureJsonData:
        apiKey: xxxxxx
        clusterId: xxxxxx

**Comment by TarasPriadka** [comment]
@aimichelle seems to be a resolved issue.
