### ISSUE TITLE
Make dashboards publicly available on Grafana Dashboards

### ISSUE THREAD

**Issue by aimichelle** [pixie-io/grafana-plugin#60]
Grafana has a marketplace for dashboards here: https://grafana.com/grafana/dashboards/ 
Currently our dashboards for Grafana are checked into this repo where they can be downloaded and imported into the Grafana UI. 
We should make them available in the marketplace for better visibility.

**Comment by htroisi** [comment]
Pixie Grafana dashboards can be found here: https://grafana.com/grafana/dashboards/?search=pixie
